function [FK_pivot,FK_tip] = autogen_fk_viz(h_f,l_f,l_s,l_spine,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f)
%AUTOGEN_FK_VIZ
%    [FK_PIVOT,FK_TIP] = AUTOGEN_FK_VIZ(H_F,L_F,L_S,L_SPINE,M_B,M_F,M_S,R,THETA_F,THETA_M,THETA_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 10:08:28

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = l_s.*m_s;
t5 = m_b+m_s;
t6 = theta_f+theta_s;
t10 = m_b.*r.*theta_m;
t7 = h_f.*t2;
t8 = l_f.*t2;
t9 = m_f+t5;
t11 = l_f.*t3;
t12 = sin(t6);
t13 = t3.*w_f;
t16 = t4+t10;
t14 = -t11;
t15 = 1.0./t9;
t17 = t5.*t11.*t15;
t18 = t12.*t15.*t16;
FK_pivot = [t14+t17+t18;t7+t8+t13];
if nargout > 1
    FK_tip = [t14+t17+t18-l_spine.*t12;t7+t8+t13+l_spine.*cos(t6)];
end
