function [FK_pivot,FK_tip] = autogen_fk_viz(l_f,l_spine,theta_f,theta_s,x_f,z_f)
%AUTOGEN_FK_VIZ
%    [FK_PIVOT,FK_TIP] = AUTOGEN_FK_VIZ(L_F,L_SPINE,THETA_F,THETA_S,X_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-May-2020 21:55:51

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = theta_f+theta_s;
t5 = l_f.*t2;
t6 = l_f.*t3;
t7 = -t6;
FK_pivot = [t7+x_f;t5+z_f];
if nargout > 1
    FK_tip = [t7+x_f-l_spine.*sin(t4);t5+z_f+l_spine.*cos(t4)];
end
