function theta_m_eq = autogen_equilibrium_motor_angle(h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_s,w_f)
%AUTOGEN_EQUILIBRIUM_MOTOR_ANGLE
%    THETA_M_EQ = AUTOGEN_EQUILIBRIUM_MOTOR_ANGLE(H_F,L_F,L_S,M_B,M_F,M_S,R,THETA_F,THETA_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 10:08:28

t2 = m_b+m_f+m_s;
theta_m_eq = -(l_s.*m_s-(t2.*(w_f.*cos(theta_f)-sin(theta_f).*(h_f+(l_f.*(m_b+m_s))./t2)))./sin(theta_f+theta_s))./(m_b.*r);
