function [FK_r_l,FK_r_r] = autogen_fk_feet(h_f,theta_f,w_f,x_f,z_f)
%AUTOGEN_FK_FEET
%    [FK_R_L,FK_R_R] = AUTOGEN_FK_FEET(H_F,THETA_F,W_F,X_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-May-2020 17:17:23

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = h_f.*t2;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = t3.*w_f;
t8 = -t4;
FK_r_l = [-t5+t6+x_f;-t7+t8+z_f];
if nargout > 1
    FK_r_r = [t5+t6+x_f;t7+t8+z_f];
end
