function [FK_com_s,FK_com_b] = autogen_fk_com(l_f,l_s,p_b,r,theta_f,theta_m,theta_s,x_f,z_f)
%AUTOGEN_FK_COM
%    [FK_COM_S,FK_COM_B] = AUTOGEN_FK_COM(L_F,L_S,P_B,R,THETA_F,THETA_M,THETA_S,X_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-May-2020 17:17:22

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = theta_f+theta_s;
t5 = l_f.*t2;
t6 = cos(t4);
t7 = l_f.*t3;
t8 = sin(t4);
t9 = -t7;
FK_com_s = [t9+x_f-l_s.*t8;t5+z_f+l_s.*t6];
if nargout > 1
    FK_com_b = [t9+x_f-p_b.*t6-r.*t8.*theta_m;t5+z_f-p_b.*t8+r.*t6.*theta_m];
end
