function [KE,PE] = autogen_energy(J_b,J_f,J_m,J_s,K,g,h_f,l_f,l_s,m_b,m_f,m_s,p_b,r,theta_f,theta_m,theta_s,theta_dot_f,theta_dot_m,theta_dot_s,x_dot_f,z_dot_f,z_f)
%AUTOGEN_ENERGY
%    [KE,PE] = AUTOGEN_ENERGY(J_B,J_F,J_M,J_S,K,G,H_F,L_F,L_S,M_B,M_F,M_S,P_B,R,THETA_F,THETA_M,THETA_S,THETA_DOT_F,THETA_DOT_M,THETA_DOT_S,X_DOT_F,Z_DOT_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-May-2020 17:17:25

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = theta_f+theta_s;
t5 = theta_dot_f+theta_dot_s;
t10 = -z_f;
t6 = l_f.*t2;
t7 = cos(t4);
t8 = l_f.*t3;
t9 = sin(t4);
t11 = t5.^2;
t12 = l_s.*t7;
t13 = p_b.*t7;
t14 = p_b.*t9;
t15 = -t6;
t16 = r.*t9.*theta_m;
t17 = r.*t7.*theta_m;
t18 = -t17;
KE = (J_b.*t11)./2.0+(J_s.*t11)./2.0+(J_m.*(t5+theta_dot_m).^2)./2.0+(m_s.*((-z_dot_f+theta_dot_f.*(t8+l_s.*t9)+l_s.*t9.*theta_dot_s).^2+(-x_dot_f+theta_dot_f.*(t6+t12)+t12.*theta_dot_s).^2))./2.0+(J_f.*theta_dot_f.^2)./2.0+(m_b.*((z_dot_f-theta_dot_s.*(t13+t16)-theta_dot_f.*(t8+t13+t16)+r.*t7.*theta_dot_m).^2+(x_dot_f+theta_dot_s.*(t14+t18)-theta_dot_f.*(t6-t14+t17)-r.*t9.*theta_dot_m).^2))./2.0+(m_f.*(x_dot_f.^2+z_dot_f.^2))./2.0;
if nargout > 1
    PE = (K.*theta_s.^2)./2.0-g.*m_b.*(h_f+l_f+t10+t14+t15+t18)-g.*m_f.*(h_f+t10)-g.*m_s.*(h_f+l_f+l_s+t10-t12+t15);
end
