function [dFK_leftfoot,dFK_rightfoot] = autogen_foot_velocities(h_f,theta_f,theta_dot_f,w_f,x_dot_f,z_dot_f)
%AUTOGEN_FOOT_VELOCITIES
%    [DFK_LEFTFOOT,DFK_RIGHTFOOT] = AUTOGEN_FOOT_VELOCITIES(H_F,THETA_F,THETA_DOT_F,W_F,X_DOT_F,Z_DOT_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-May-2020 20:50:47

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = h_f.*t2;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = t3.*w_f;
dFK_leftfoot = [x_dot_f+theta_dot_f.*(t4+t7);z_dot_f-theta_dot_f.*(t5-t6)];
if nargout > 1
    dFK_rightfoot = [x_dot_f+theta_dot_f.*(t4-t7);z_dot_f+theta_dot_f.*(t5+t6)];
end
