function C_unilateral = autogen_constraints(h_b,h_f,l_spine,n_lx,n_lz,n_rx,n_rz,p_lx,p_lz,p_rx,p_rz,r,theta_f,theta_m,w_f,x_f,z_f)
%AUTOGEN_CONSTRAINTS
%    C_UNILATERAL = AUTOGEN_CONSTRAINTS(H_B,H_F,L_SPINE,N_LX,N_LZ,N_RX,N_RZ,P_LX,P_LZ,P_RX,P_RZ,R,THETA_F,THETA_M,W_F,X_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    13-May-2020 20:50:46

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = r.*theta_m;
t9 = -z_f;
t10 = h_b./2.0;
t5 = h_f.*t2;
t6 = t2.*w_f;
t7 = h_f.*t3;
t8 = t3.*w_f;
C_unilateral = [-n_lx.*(p_lx+t6-t7-x_f)-n_lz.*(p_lz+t5+t8+t9);-n_rz.*(p_rz+t5-t8+t9)+n_rx.*(-p_rx+t6+t7+x_f);-l_spine+t4+t10;-t4+t10];
