function [C_bilateral,C_unilateral] = autogen_constraints(h_b,h_f,l_spine,r,theta_f,theta_m,w_f,x_f,z_f)
%AUTOGEN_CONSTRAINTS
%    [C_BILATERAL,C_UNILATERAL] = AUTOGEN_CONSTRAINTS(H_B,H_F,L_SPINE,R,THETA_F,THETA_M,W_F,X_F,Z_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-May-2020 21:55:52

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = r.*theta_m;
t8 = -z_f;
t5 = h_f.*t2;
t6 = h_f.*t3;
t7 = t3.*w_f;
t9 = t2-1.0;
t10 = t9.*w_f;
C_bilateral = [t6-t10+x_f;t6+t10+x_f];
if nargout > 1
    C_unilateral = [t5+t7+t8;t5-t7+t8;h_b./2.0-l_spine+t4;h_b./2.0-t4];
end
