function G_q = autogen_conservative_forces(K,g,h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f)
%AUTOGEN_CONSERVATIVE_FORCES
%    G_Q = AUTOGEN_CONSERVATIVE_FORCES(K,G,H_F,L_F,L_S,M_B,M_F,M_S,R,THETA_F,THETA_M,THETA_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 10:09:25

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = theta_f+theta_s;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = l_f.*t3;
t8 = sin(t4);
t9 = -t5;
G_q = [-g.*m_s.*(t6+t7+t9+l_s.*t8)-g.*m_b.*(t6+t7+t9+r.*t8.*theta_m)+g.*m_f.*(t5-t6),K.*theta_s-g.*l_s.*m_s.*t8-g.*m_b.*r.*t8.*theta_m,g.*m_b.*r.*cos(t4)];
