function [A_unilateral,H_cl,H_cr,H_ctop,H_cbot] = autogen_constraint_derivatives(h_f,n_lx,n_lz,n_rx,n_rz,r,theta_f,w_f)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_UNILATERAL,H_CL,H_CR,H_CTOP,H_CBOT] = AUTOGEN_CONSTRAINT_DERIVATIVES(H_F,N_LX,N_LZ,N_RX,N_RZ,R,THETA_F,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-May-2020 17:17:24

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = h_f.*t2;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = t3.*w_f;
t8 = -t6;
t9 = -t7;
t10 = t4+t7;
t11 = t5+t6;
t12 = t4+t9;
t13 = t5+t8;
A_unilateral = reshape([n_lx,n_rx,0.0,0.0,n_lz,n_rz,0.0,0.0,n_lx.*t10-n_lz.*t13,n_rx.*t12+n_rz.*t11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,r,-r],[4,5]);
if nargout > 1
    H_cl = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,n_lz.*t10+n_lx.*t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 2
    H_cr = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-n_rx.*t11+n_rz.*t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 3
    H_ctop = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 4
    H_cbot = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
