function [A_all,H_clx,H_clz,H_crx,H_crz] = autogen_constraint_derivatives(h_f,theta_f,w_f)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_ALL,H_CLX,H_CLZ,H_CRX,H_CRZ] = AUTOGEN_CONSTRAINT_DERIVATIVES(H_F,THETA_F,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 15:40:47

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = h_f.*t2;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = t3.*w_f;
t8 = -t4;
t9 = -t5;
t10 = -t6;
t11 = -t7;
t12 = t5+t10;
t13 = t9+t10;
A_all = reshape([1.0,0.0,1.0,0.0,0.0,-1.0,0.0,-1.0,t4+t7,t12,t4+t11,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,5]);
if nargout > 1
    H_clx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 2
    H_clz = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t8+t11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 3
    H_crx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 4
    H_crz = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7+t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
