function G_jac = autogen_derivative_conservative_forces(K,g,h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f)
%AUTOGEN_DERIVATIVE_CONSERVATIVE_FORCES
%    G_JAC = AUTOGEN_DERIVATIVE_CONSERVATIVE_FORCES(K,G,H_F,L_F,L_S,M_B,M_F,M_S,R,THETA_F,THETA_M,THETA_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 10:09:25

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = l_s.*m_s;
t5 = theta_f+theta_s;
t9 = m_b.*r.*theta_m;
t6 = h_f.*t2;
t7 = l_f.*t2;
t8 = cos(t5);
t10 = sin(t5);
t11 = t3.*w_f;
t12 = t4+t9;
t13 = g.*m_b.*r.*t10;
t15 = g.*t8.*t12;
t14 = -t13;
t16 = -t15;
G_jac = reshape([-g.*m_s.*(t6+t7+t11+l_s.*t8)-g.*m_f.*(t6+t11)-g.*m_b.*(t6+t7+t11+r.*t8.*theta_m),t16,t14,t16,K-g.*t4.*t8-g.*t8.*t9,t14,t14,t14,0.0],[3,3]);
