function [A_bilateral,A_unilateral,H_clx,H_crx,H_clz,H_crz,H_ctop,H_cbot] = autogen_constraint_derivatives(h_f,r,theta_f,w_f)
%AUTOGEN_CONSTRAINT_DERIVATIVES
%    [A_BILATERAL,A_UNILATERAL,H_CLX,H_CRX,H_CLZ,H_CRZ,H_CTOP,H_CBOT] = AUTOGEN_CONSTRAINT_DERIVATIVES(H_F,R,THETA_F,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    04-May-2020 21:55:54

t2 = cos(theta_f);
t3 = sin(theta_f);
t4 = h_f.*t2;
t5 = t2.*w_f;
t6 = h_f.*t3;
t7 = t3.*w_f;
t8 = -t4;
t9 = -t5;
t10 = -t6;
t11 = -t7;
A_bilateral = reshape([1.0,1.0,0.0,0.0,t4+t7,t4+t11,0.0,0.0,0.0,0.0],[2,5]);
if nargout > 1
    t12 = t5+t10;
    t13 = t9+t10;
    A_unilateral = reshape([0.0,0.0,0.0,0.0,-1.0,-1.0,0.0,0.0,t12,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,r,-r],[4,5]);
end
if nargout > 2
    H_clx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 3
    H_crx = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 4
    H_clz = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t8+t11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 5
    H_crz = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7+t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 6
    H_ctop = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
if nargout > 7
    H_cbot = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[5,5]);
end
