function x_wheel = autogen_wheel_position(h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f)
%AUTOGEN_WHEEL_POSITION
%    X_WHEEL = AUTOGEN_WHEEL_POSITION(H_F,L_F,L_S,M_B,M_F,M_S,R,THETA_F,THETA_M,THETA_S,W_F)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 10:08:27

t2 = sin(theta_f);
t3 = m_b+m_f+m_s;
t4 = 1.0./t3;
x_wheel = h_f.*t2-w_f.*cos(theta_f)+t4.*sin(theta_f+theta_s).*(l_s.*m_s+m_b.*r.*theta_m)+l_f.*t2.*t4.*(m_b+m_s);
