%% conservative_forces.m
%
% Description:
%   Wrapper function for autogen_conservative_forces.m
%   Computes the gravitational and elastic forces on the robot
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   G = values of three conservative forces

function [G] = conservative_forces(x,params)

theta_f = x(1);
theta_m = x(3);
theta_s = x(2);

K = params.model.dyn.K;
g = params.model.dyn.g;
h_f = params.model.geom.foot.hbot;
l_f = params.model.geom.foot.htop;
l_s = params.model.geom.spine.l;
m_b = params.model.dyn.body.m;
m_f = params.model.dyn.foot.m;
m_s = params.model.dyn.spine.m;
r = params.model.geom.body.r;
w_f = params.model.geom.foot.w;

G = autogen_conservative_forces(K,g,h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f);
end

