%% constraints.m
%
% Description:
%   Wrapper function for autogen_fk_viz.m
%   Computes the locations of the pivot and the spine tip of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   C_all = values of three constraint equations

function [C_bilateral,C_unilateral] = constraints(x,params)

x_f = x(1);
z_f = x(2);
theta_f = x(3);
theta_m = x(5);

h_b = params.model.geom.body.h;
h_f = params.model.geom.foot.hbot;
l_spine = params.model.geom.spine.h;
r = params.model.geom.body.r;
w_f = params.model.geom.foot.w;

[C_bilateral,C_unilateral] = autogen_constraints(h_b,h_f,l_spine,r,theta_f,theta_m,w_f,x_f,z_f);

end

