%% constraints.m
%
% Description:
%   Wrapper function for autogen_fk_viz.m
%   Computes the locations of the pivot and the spine tip of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   C_all = values of three constraint equations

function [C_all] = constraints(x,params)

x_f = x(1);
z_f = x(2);
theta_f = x(3);

h_f = params.model.geom.foot.hbot;
w_f = params.model.geom.foot.w;

C_all = autogen_constraints(h_f,theta_f,w_f,x_f,z_f);

end

