%% constraint_derivatives.m
%
% Description:
%   Wrapper function for autogen_constraint_derivatives.m
%   Computes the constraint jacobian and hessians for the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot; s];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   A_unilateral: a 4x5 jacobian of constraint equation derivatives.  If only a
%   subset of constraints are active, then only those rows of A_unilateral will be
%   used to compute the A matrix for that situation.
%
%   Hessian is a 5x5x4 array of constraint second derivatives.

function [A_unilateral,Hessian_unilateral] = constraint_derivatives(x,params)

theta_f = x(3);

h_f = params.model.geom.foot.hbot;
w_f = params.model.geom.foot.w;
r = params.model.geom.body.r;

[~,~,n_l] = track(x(11),params);
[~,~,n_r] = track(x(12),params);

n_lx = n_l(1);
n_lz = n_l(2);
n_rx = n_r(1);
n_rz = n_r(2);

[A_unilateral,H_cl,H_cr,H_ctop,H_cbot] = autogen_constraint_derivatives(h_f,n_lx,n_lz,n_rx,n_rz,r,theta_f,w_f);
Hessian_unilateral = cat(3,H_cl,H_cr,H_ctop,H_cbot);  

end

