%% equilibrium_motor_angle.m
%
% Description:
%   Wrapper function for autogen_equilibrium_motor_angle.m
%   Computes the body motor rotation needed to put the robot in an
%   equilibrium configuration, given theta_f and theta_s
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   theta_m_eq = values of motor angle that establishes equilibrium

function [theta_m_eq] = equilibrium_motor_angle(x,params)

theta_f = x(1);
theta_s = x(2);

h_f = params.model.geom.foot.hbot;
l_f = params.model.geom.foot.htop;
l_s = params.model.geom.spine.l;
m_b = params.model.dyn.body.m;
m_f = params.model.dyn.foot.m;
m_s = params.model.dyn.spine.m;
r = params.model.geom.body.r;
w_f = params.model.geom.foot.w;

theta_m_eq = autogen_equilibrium_motor_angle(h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_s,w_f);
end

