%% foot_velocities.m
%
% Description:
%   Wrapper function for autogen_foot_velocities.m
%   Computes the velocities of the left and right feet of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot; s];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   v_l, v_r = foot velocities

function [v_l,v_r] = foot_velocities(x,params)

theta_f = x(3);
theta_dot_f = x(8);
x_dot_f = x(6);
z_dot_f = x(7);

h_f = params.model.geom.foot.hbot;
w_f = params.model.geom.foot.w;

[v_l,v_r] = autogen_foot_velocities(h_f,theta_f,theta_dot_f,w_f,x_dot_f,z_dot_f);

end
