%% H_eom.m
%
% Description:
%   Wrapper function for autogen_H.m
%   Computes H(q,q_dot) for the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   H: a 5x1 set of terms.

function H = H_eom(x,params)

theta_f = x(3);
theta_m = x(5);
theta_s = x(4);
theta_dot_f = x(8);
theta_dot_m = x(10);
theta_dot_s = x(9);

K = params.model.dyn.K;
g = params.model.dyn.g;
l_f = params.model.geom.foot.htop;
l_s = params.model.geom.spine.l;
m_b = params.model.dyn.body.m;
m_f = params.model.dyn.foot.m;
m_s = params.model.dyn.spine.m;
p_b = params.model.geom.body.pb;
r = params.model.geom.body.r;

H = autogen_H_eom(K,g,l_f,l_s,m_b,m_f,m_s,p_b,r,theta_f,theta_m,theta_s,theta_dot_f,theta_dot_m,theta_dot_s);

end

