%% inv_mass_matrix.m
%
% Description:
%   Wrapper function for autogen_inverse_mass_matrix.m
%   Computes the mass matrix of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   Minv: a 5x5 inverse mass matrix for the robot.

function Minv = inv_mass_matrix(x,params)

theta_f = x(3);
theta_m = x(5);
theta_s = x(4);

J_b = params.model.dyn.body.J;
J_f = params.model.dyn.foot.J;
J_m = params.model.dyn.body.Jm;
J_s = params.model.dyn.spine.J;
l_f = params.model.geom.foot.htop;
l_s = params.model.geom.spine.l;
m_b = params.model.dyn.body.m;
m_f = params.model.dyn.foot.m;
m_s = params.model.dyn.spine.m;
p_b = params.model.geom.body.pb;
r = params.model.geom.body.r;

Minv = autogen_inverse_mass_matrix(J_b,J_f,J_m,J_s,l_f,l_s,m_b,m_f,m_s,p_b,r,theta_f,theta_m,theta_s);

end

