%% mass_matrix.m
%
% Description:
%   Wrapper function for autogen_mass_matrix.m
%   Computes the mass matrix of the jumping robot.
%
% Inputs:
%   x: the state vector, x = [q; q_dot];
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   M: a 5x5 mass matrix for the robot.

function M = mass_matrix(x,params)

theta_f = x(1);
theta_m = x(3);
theta_s = x(2);

J_b = params.model.dyn.body.J;
J_f = params.model.dyn.foot.J;
J_m = params.model.dyn.body.Jm;
J_s = params.model.dyn.spine.J;
h_f = params.model.geom.foot.hbot;
l_f = params.model.geom.foot.htop;
l_s = params.model.geom.spine.l;
m_b = params.model.dyn.body.m;
m_f = params.model.dyn.foot.m;
m_s = params.model.dyn.spine.m;
r = params.model.geom.body.r;
w_f = params.model.geom.foot.w;

M = autogen_mass_matrix(J_b,J_f,J_m,J_s,h_f,l_f,l_s,m_b,m_f,m_s,r,theta_f,theta_m,theta_s,w_f);

end

