%% update_events.m
%
% Description:
%   function that computes the 4x1 vector of data from which events are
%   detected
%
% Inputs:
%   x: the 10x1 vector of states
%   F_active: the active forces as computed by robot_dynamics
%   params: a struct with many elements, generated by calling init_params.m
%
% Outputs:
%   events: a 4x1 vector in which each element is either a constraint
%   equation value or a constraint force value

function [events] = update_events(x,F_active,params)

events = zeros(4,1);

[~,C_unilateral] = constraints(x,params);  
C_unilateral = -C_unilateral;       % change the sign so that this, like the force, goes negative to indicate an event

if sum(F_active) == 0
    events = C_unilateral;
    
else
    i_force = 0;
    for ic=1:4
        if params.sim.constraints.uni(ic) == 1    % if a unilateral constraint is active, then monitor force
            i_force = i_force + 1;
            events(ic) = F_active(i_force);
        else
            events(ic) = C_unilateral(ic);   % if a constraint is not active, monitor the constraint equation
        end
    end

end


